# Schema for the configuration files of the Federation module.
federation.settings:
  type: config_object
  label: 'Federation settings'
  mapping:
    federation:
      type: string
      label: 'Federation'
